// This file was auto-generated by ML.NET Model Builder.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace DecisionTreeRegression
{
    public partial class DTRegression
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Relative_Compactness", @"Relative_Compactness"),new InputOutputColumnPair(@"Surface_Area", @"Surface_Area"),new InputOutputColumnPair(@"Wall_Area", @"Wall_Area"),new InputOutputColumnPair(@"Roof_Area", @"Roof_Area"),new InputOutputColumnPair(@"Overall_Height", @"Overall_Height"),new InputOutputColumnPair(@"Orientation", @"Orientation"),new InputOutputColumnPair(@"Glazing_Area", @"Glazing_Area"),new InputOutputColumnPair(@"Glazing_Area_Distribution", @"Glazing_Area_Distribution")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Relative_Compactness",@"Surface_Area",@"Wall_Area",@"Roof_Area",@"Overall_Height",@"Orientation",@"Glazing_Area",@"Glazing_Area_Distribution"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=11,MinimumExampleCountPerLeaf=10,NumberOfTrees=113,MaximumBinCountPerFeature=427,FeatureFraction=0.99999999,LearningRate=0.999999776672986,LabelColumnName=@"Heating_Load",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
