// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace DecisionTreeRegression
{
    public partial class DTRegression
    {
        /// <summary>
        /// model input class for DTRegression.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Relative_Compactness")]
            public float Relative_Compactness { get; set; }

            [ColumnName(@"Surface_Area")]
            public float Surface_Area { get; set; }

            [ColumnName(@"Wall_Area")]
            public float Wall_Area { get; set; }

            [ColumnName(@"Roof_Area")]
            public float Roof_Area { get; set; }

            [ColumnName(@"Overall_Height")]
            public float Overall_Height { get; set; }

            [ColumnName(@"Orientation")]
            public float Orientation { get; set; }

            [ColumnName(@"Glazing_Area")]
            public float Glazing_Area { get; set; }

            [ColumnName(@"Glazing_Area_Distribution")]
            public float Glazing_Area_Distribution { get; set; }

            [ColumnName(@"Heating_Load")]
            public float Heating_Load { get; set; }

            [ColumnName(@"Cooling_Load")]
            public float Cooling_Load { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DTRegression.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Relative_Compactness")]
            public float Relative_Compactness { get; set; }

            [ColumnName(@"Surface_Area")]
            public float Surface_Area { get; set; }

            [ColumnName(@"Wall_Area")]
            public float Wall_Area { get; set; }

            [ColumnName(@"Roof_Area")]
            public float Roof_Area { get; set; }

            [ColumnName(@"Overall_Height")]
            public float Overall_Height { get; set; }

            [ColumnName(@"Orientation")]
            public float Orientation { get; set; }

            [ColumnName(@"Glazing_Area")]
            public float Glazing_Area { get; set; }

            [ColumnName(@"Glazing_Area_Distribution")]
            public float Glazing_Area_Distribution { get; set; }

            [ColumnName(@"Heating_Load")]
            public float Heating_Load { get; set; }

            [ColumnName(@"Cooling_Load")]
            public float Cooling_Load { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("DTRegression.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
