// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace LinearRegression
{
    public partial class Regression
    {
        /// <summary>
        /// model input class for Regression.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"No")]
            public float No { get; set; }

            [ColumnName(@"X1 transaction date")]
            public float X1_transaction_date { get; set; }

            [ColumnName(@"X2 house age")]
            public float X2_house_age { get; set; }

            [ColumnName(@"X3 distance to the nearest MRT station")]
            public float X3_distance_to_the_nearest_MRT_station { get; set; }

            [ColumnName(@"X4 number of convenience stores")]
            public float X4_number_of_convenience_stores { get; set; }

            [ColumnName(@"X5 latitude")]
            public float X5_latitude { get; set; }

            [ColumnName(@"X6 longitude")]
            public float X6_longitude { get; set; }

            [ColumnName(@"Y house price of unit area")]
            public float Y_house_price_of_unit_area { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Regression.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"No")]
            public float No { get; set; }

            [ColumnName(@"X1 transaction date")]
            public float X1_transaction_date { get; set; }

            [ColumnName(@"X2 house age")]
            public float X2_house_age { get; set; }

            [ColumnName(@"X3 distance to the nearest MRT station")]
            public float X3_distance_to_the_nearest_MRT_station { get; set; }

            [ColumnName(@"X4 number of convenience stores")]
            public float X4_number_of_convenience_stores { get; set; }

            [ColumnName(@"X5 latitude")]
            public float X5_latitude { get; set; }

            [ColumnName(@"X6 longitude")]
            public float X6_longitude { get; set; }

            [ColumnName(@"Y house price of unit area")]
            public float Y_house_price_of_unit_area { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Regression.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
