// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MulticlassClassification
{
    public partial class MClassification
    {
        /// <summary>
        /// model input class for MClassification.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Carat Weight")]
            public float Carat_Weight { get; set; }

            [ColumnName(@"Cut")]
            public string Cut { get; set; }

            [ColumnName(@"Color")]
            public string Color { get; set; }

            [ColumnName(@"Clarity")]
            public string Clarity { get; set; }

            [ColumnName(@"Polish")]
            public string Polish { get; set; }

            [ColumnName(@"Symmetry")]
            public string Symmetry { get; set; }

            [ColumnName(@"Report")]
            public string Report { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MClassification.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Carat Weight")]
            public float Carat_Weight { get; set; }

            [ColumnName(@"Cut")]
            public uint Cut { get; set; }

            [ColumnName(@"Color")]
            public float[] Color { get; set; }

            [ColumnName(@"Clarity")]
            public float[] Clarity { get; set; }

            [ColumnName(@"Polish")]
            public float[] Polish { get; set; }

            [ColumnName(@"Symmetry")]
            public float[] Symmetry { get; set; }

            [ColumnName(@"Report")]
            public float[] Report { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MClassification.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
